services:
  tunnel:
    container_name: tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    network_mode: host
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock
    env_file:
      - /environment/tunnel-ipv6.env
